# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-24 00:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='checked',
            field=models.ManyToManyField(blank=True, related_name='is_checked', to=settings.AUTH_USER_MODEL),
        ),
    ]
