# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-25 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20180424_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='showTopics',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='showUsers',
            field=models.BooleanField(default=False),
        ),
    ]
