# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-25 20:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20180425_0234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='showTopics',
            new_name='showAllTopics',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='showUsers',
            new_name='showAllUsers',
        ),
    ]
