# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-05 22:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0004_question_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='viewers',
            field=models.ManyToManyField(blank=True, related_name='is_viewing_question', to=settings.AUTH_USER_MODEL),
        ),
    ]
