# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-06 23:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_question_viewers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='is_following_question', to=settings.AUTH_USER_MODEL),
        ),
    ]
