# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-28 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='name',
        ),
        migrations.AddField(
            model_name='answer',
            name='contents',
            field=models.TextField(default=1, help_text='Type Answer Here...'),
            preserve_default=False,
        ),
    ]
