# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-28 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20180428_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='contents',
        ),
        migrations.AddField(
            model_name='answer',
            name='message',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
