# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-28 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_auto_20180428_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
