# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-28 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0010_auto_20180428_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='name',
            field=models.TextField(blank=True, default='default answer', null=True),
        ),
    ]
