# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-30 19:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feedback', '0016_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='commentors',
            field=models.ManyToManyField(blank=True, related_name='is_commenting', to=settings.AUTH_USER_MODEL),
        ),
    ]
