# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-05 21:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0017_answer_commentors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='commentors',
            field=models.ManyToManyField(blank=True, related_name='is_replying_answer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='answer',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='is_following_answer', to=settings.AUTH_USER_MODEL),
        ),
    ]
