# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-05 21:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0018_auto_20180505_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='is_following_comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
