# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-24 01:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('topics', '0003_auto_20180424_0051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='display',
        ),
        migrations.AddField(
            model_name='topic',
            name='viewers',
            field=models.ManyToManyField(blank=True, related_name='is_viewingT', to=settings.AUTH_USER_MODEL),
        ),
    ]
