# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-06 23:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0004_auto_20180424_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='is_following_topic', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='topic',
            name='viewers',
            field=models.ManyToManyField(blank=True, related_name='is_viewing_topic', to=settings.AUTH_USER_MODEL),
        ),
    ]
